# Neuroconductor Template ANTs
language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl

os:
  - linux
  - osx

r_check_args: --as-cran
# r_check_args: "--as-cran --install-args=--build"


before_install:
  - export RGL_USE_NULL=TRUE
  - export PROJ_DIR=`basename $PWD`
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  #- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
  - cat DESCRIPTION
  - start_xvfb ;
  - no_open_mp ;   
  - remove_neuroc_packages
  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
  # does all the clang exports
  - x=`export_clang_cxx`; eval ${x}
  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
  - clang_cxx
  - export cmake_version="3.11"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version
#  - export ants_user=muschellij2
  - export ants_user=neuroconductor-devel
  - install_missing_remote_deps ${ants_user}/ITKR ${ants_user}/ANTsRCore ${ants_user}/ANTsR
  - echo "Done Installing Missing Deps"
  - gh_binary_install ${ants_user}/ITKR
  - gh_binary_install ${ants_user}/ANTsRCore
  - gh_binary_install ${ants_user}/ANTsR
  - cat DESCRIPTION
  - install_remotes_no_dep
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`

after_success:
  - cat ${PACKAGE_NAME}.Rcheck/00install.out
  - cat ${PACKAGE_NAME}.Rcheck/00check.log

after_failure:
  - cat ${PACKAGE_NAME}.Rcheck/00install.out
  - cat ${PACKAGE_NAME}.Rcheck/00check.log

# need this explicitly
# for naming convention
before_deploy:
  - R CMD INSTALL --build ${PKG_TARBALL}
  # so no overwrite of linux build
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
    rm -f *.tar.gz ;
    fi

after_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then 
      Rscript -e 'covr::coveralls(type = "all")' ;
    fi


