# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx

env:
  global: RGL_USE_NULL=TRUE
  
r_check_args: "--as-cran --install-args=--build"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libcgal-dev libglu1-mesa-dev mesa-common-dev; fi
  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
  - source travis_helpers.sh
  - rm travis_helpers.sh
  - PACKAGE_NAME=`package_name`
  - PACKAGE_DIRECTORY=`basename ${PWD}`
  
apt_packages:
  - texinfo

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - cat ${PWD}.Rcheck/00install.out
  - cat ${PWD}.Rcheck/00check.log

notifications:
  email:
    on_success: change
    on_failure: change
